version: "3.4"
services:
  server:
    build:
      context: .
      target: development
    container_name: doc-gallery-development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=3000
    ports:
      - 3000:3000
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
